
package com.maki.toni;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BankInterface", targetNamespace = "http://toni.wst.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.TransferResponse")
    public String transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.maki.toni.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountInformation", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.GetAccountInformation")
    @ResponseWrapper(localName = "getAccountInformationResponse", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.GetAccountInformationResponse")
    public Account getAccountInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.maki.toni.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.WithdrawResponse")
    public Account withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Account arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.maki.toni.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.DepositResponse")
    public Account deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Account arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.maki.toni.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://toni.wst.com/", className = "com.maki.toni.CreateAccountResponse")
    public Account createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
