
package com.maki.toni;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SellerImplementationService", targetNamespace = "http://toni.maki.com/", wsdlLocation = "http://localhost:8080/WS/Sell?wsdl")
public class SellerImplementationService
    extends Service
{

    private final static URL SELLERIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.maki.toni.SellerImplementationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.maki.toni.SellerImplementationService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WS/Sell?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WS/Sell?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SELLERIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
    }

    public SellerImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SellerImplementationService() {
        super(SELLERIMPLEMENTATIONSERVICE_WSDL_LOCATION, new QName("http://toni.maki.com/", "SellerImplementationService"));
    }

    /**
     * 
     * @return
     *     returns SellerInterface
     */
    @WebEndpoint(name = "SellerImplementationPort")
    public SellerInterface getSellerImplementationPort() {
        return super.getPort(new QName("http://toni.maki.com/", "SellerImplementationPort"), SellerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerInterface
     */
    @WebEndpoint(name = "SellerImplementationPort")
    public SellerInterface getSellerImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://toni.maki.com/", "SellerImplementationPort"), SellerInterface.class, features);
    }

}
