
package com.maki.toni;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SellerInterface", targetNamespace = "http://toni.maki.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SellerInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.CreateResponse")
    public boolean create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.maki.toni.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBooks", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.SearchBooks")
    @ResponseWrapper(localName = "searchBooksResponse", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.SearchBooksResponse")
    public List<Book> searchBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.maki.toni.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRating", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.GetRating")
    @ResponseWrapper(localName = "getRatingResponse", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.GetRatingResponse")
    public Book getRating(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderBook", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.OrderBook")
    @ResponseWrapper(localName = "orderBookResponse", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.OrderBookResponse")
    public int orderBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://toni.maki.com/", className = "com.maki.toni.DepositResponse")
    public double deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
